services:
  app:
    image: ghcr.io/magmast/chat
    ports:
      - 3000:3000
    restart: unless-stopped
    env_file:
      - .env.local
    depends_on:
      - db

  migrate:
    image: ghcr.io/magmast/chat-migrate
    profiles:
      - migrate
    env_file:
      - .env.local
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env.local
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
