services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: 0841d2e8dcba5384ae2b56c512c5a609
      POSTGRES_DB: chatbot
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data:
